"""Every repo path the operator docs point at must exist.

WHY. On 2026-07-30 the README told Windows operators to run `.\\kit\\IR-Collect.ps1` six times.
kit/ was renamed to collectors/ long ago; the Linux command lines were updated and the Windows
ones were not. A reader following the README verbatim got a file-not-found from PowerShell, and
the same stale path sat in docs/RUNBOOK.md and docs/RANGE.md. The catalogue already had a check
like this - the operator docs did not.

TWO THINGS THIS HAS TO GET RIGHT or it becomes a check that cries wolf and gets switched off:

  GLOBS. The docs legitimately write `collectors/fetch-tools.*` and `tools/PROVENANCE-*.txt` to
  mean "both variants". A naive extractor truncates those and reports them missing. A path whose
  matched text is followed by `*` is treated as a glob and satisfied by ANY match.

  UNCOMMITTED OUTPUTS. Some referenced paths are produced, not stored: the fetched tool payload
  and a generated IOC file. Those are allowlisted individually WITH A REASON, not by a blanket
  pattern, so a genuinely missing file cannot hide behind a category.

Usage: check-doc-paths.py <repo-root>
Prints one line per problem, then "TOTAL <n> MISSING <m>". Exit 2 if it cannot scan.
"""
import glob as globmod
import io
import os
import re
import sys

BS = chr(92)
SEP = '[/' + BS + BS + ']'
CHARS = '[A-Za-z0-9_./' + BS + BS + '-]+'

# TWO extraction rules, and the second one is not optional.
#
# Rule 1 matches paths that begin with a known top-level directory, which catches prose like
# `collectors/fetch-tools.*`. Rule 1 ALONE was the first version of this checker - and when the
# original defect was re-introduced as a mutation test, it PASSED. `kit` is not a known top-level
# directory, so a guard built only from rule 1 could not detect the very stale path it was written
# to prevent: a check that cannot catch its own motivating defect is theatre.
#
# Rule 2 matches an explicit repo-relative prefix - `./x/y` or `.\x\y` - which is exactly how the
# docs write runnable commands, and it does not care what the directory is called. That is what
# makes a renamed-away directory detectable.
PATS = [
    re.compile(r'\b(collectors|tests|docs|tools|mobile|range|detection)' + SEP + CHARS),
    re.compile(r'\.' + SEP + CHARS),
]

# Referenced by the docs but produced rather than committed. Each entry names WHY, because a
# category-shaped exclusion would let a real absence hide inside it.
ALLOWED = {
    'tools/bin': 'the fetched tool payload - built by collectors/fetch-tools.*, never committed',
    'detection/mobile_iocs.csv': 'generated by the mobile pipeline; an output, not a source file',
    'tools/PROVENANCE-': 'tools/PROVENANCE-*.txt is written by fetch-tools at build time; the glob '
                         'has nothing to match in a clean checkout, which is correct',
}


def main(argv):
    if len(argv) != 2:
        print('usage: check-doc-paths.py <repo-root>')
        return 2
    root = argv[1]
    docs = [os.path.join(root, 'README.md')] + sorted(globmod.glob(os.path.join(root, 'docs', '*.md')))
    docs = [d for d in docs if os.path.isfile(d)]
    if not docs:
        print('NO DOCS FOUND under %s - refusing to report clean' % root)
        return 2

    total = 0
    missing = []
    for d in docs:
        try:
            s = io.open(d, encoding='utf-8', errors='replace').read()
        except OSError as e:
            print('CANNOT READ %s: %s' % (d, e))
            return 2
        hits = {}
        for pat in PATS:
            for m in pat.finditer(s):
                hits[m.start()] = m
        for _, m in sorted(hits.items()):
            raw = m.group(0)
            after = s[m.end():m.end() + 1]
            # normalise before the allowlist lookup: a trailing slash is the same directory,
            # and a leading ./ or .\ is repo-relative rather than part of the name
            p = raw.replace(BS, '/').rstrip('.,`)').rstrip('/')
            if p.startswith('./'):
                p = p[2:]
            if not p or '/' not in p:
                continue
            total += 1
            if p in ALLOWED:
                continue
            full = os.path.join(root, p)
            # a trailing * (or a stripped trailing dot before one) means the doc wrote a glob
            if after == '*' or raw.endswith('.'):
                if globmod.glob(full + '*'):
                    continue
            if os.path.exists(full):
                continue
            missing.append((os.path.basename(d), p))

    seen = set()
    for d, p in missing:
        if p in seen:
            continue
        seen.add(p)
        print('  MISSING %-30s referenced by %s' % (p, d))
    print('TOTAL %d MISSING %d' % (total, len(seen)))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
